export const ADD_TO_NUMBERS = "ADD_TO_NUMBERS";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_LOADED = "PAGE_LOADED";
export const LOGIN_USER = "LOGIN_USER";
export const DASHBOARD_DETAILS = "DASHBOARD_DETAILS";
export const WALLET_DETAILS = "WALLET_DETAILS";
export const REDEEM_COIN_DETAILS = "REDEEM_COIN_DETAILS";
